		LOC Data_Segment
		GREG @
X1		OCTA	#7FFFFFFFFFFFFFFF
X2		OCTA	#7FFFFFFFFFFFFFFF
X3		OCTA	#FFFFFFFFFFFFFFFF
X4		OCTA	#FFFFFFFFFFFFFFFF


Main	LDO		$1,X1
		LDO		$2,X2
		ADD		$3,$1,$2
		LDOU	$1,X3
		LDOU	$2,X4
		ADDU	$3,$1,$2